Develop
incredet/group_project_pazzle pull request #7
Opened 2023-02-08 14:04 UTC by incredet

2023-02-13 09:15 UTC, kostyantynHrytsyuk requested changes
Привіт!

Особливих зауважень в мене немає

Лише зробіть develop гілкою по замовчуванню
І допишіть if __name__ (додав це як коментар)

Як зробите - напишіть мені повідомлення

2023-02-13 09:15 UTC, kostyantynHrytsyuk commented on pazzle.py
> +    return validate_row(board) and val_column(board) and check_color(board)
Додайте в кінець файлу конструкцію if __name__

2023-02-16 13:44 UTC, kostyantynHrytsyuk approved these changes
З моєї сторони зауважень немає

Але тут є merge conflicts

Виправте їх та завершіть merge

Тоді я виставлю команді додатковий бал

2023-02-16 13:48 UTC, merged

2023-02-16 13:48 UTC, incredet commented
@kostyantynHrytsyuk завершили

2023-02-16 13:51 UTC, kostyantynHrytsyuk commented
@incredet , Чудово, дякую, що повідомили

Гарна робота!